name: Node.js Express App CI

on:
  push:
    paths:
      - 'tugas-express-api/**'
  pull_request:
    paths:
      - 'tugas-express-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: JS
      run: npm install

    - name: Run Tests (optional)
      working-directory: JS
      run: npm test
